query GetEvents($first: Int!) {
  events(first: $first) {
    data {
      id
      title
      description
      start_date
      end_date
      location
      zone_id
      zone {
        id
        zone_name
      }
      status
    }
  }
}
