services:
  ui:
    image: node:20
    container_name: angular-ui
    working_dir: /app
    volumes:
      - ../ui:/app
    ports:
      - "4200:4200"
    environment:
      NG_CLI_ANALYTICS: "false"
    command: >
      sh -c "npx ng serve --host 0.0.0.0 --port 4200 --proxy-config proxy.conf.json"
    stdin_open: true
    tty: true

  api:
    image: webdevops/php-apache:8.4
    container_name: brgy-api
    working_dir: /var/www
    volumes:
      - ../api:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: app_db
      DB_USERNAME: app_user
      DB_PASSWORD: secret
      CACHE_STORE: file
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
