import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideIcons } from '@ng-icons/core';
import {
  heroHomeModern,
  heroUsers,
  heroUserGroup,
  heroShieldCheck,
  heroDocumentText,
  heroPresentationChartLine,
  heroBell,
  heroCalendar,
  heroMap,
  heroChatBubbleLeftRight,
  heroCog6Tooth,
  heroArrowRightOnRectangle,
  heroBars3,
  heroXMark,
  heroMagnifyingGlass,
  heroPlus,
  heroPencil,
  heroTrash,
  heroEye,
  heroEyeSlash,
  heroChevronRight,
  heroChevronDown,
  heroChevronUp,
  heroChevronLeft,
  heroCheck,
  heroExclamationTriangle,
  heroInformationCircle,
  heroArrowPath,
  heroArrowsPointingOut,
  heroArrowsPointingIn,
  heroBuildingLibrary,
  heroFingerPrint,
  heroIdentification,
  heroBriefcase,
  heroChartBar,
  heroClipboardDocumentCheck,
  heroSquare3Stack3d,
  heroArchiveBox,
  heroQueueList,
  heroUserCircle,
  heroBuildingOffice2,
  heroShieldExclamation,
  heroCheckCircle,
  heroExclamationCircle
} from '@ng-icons/heroicons/outline';
import {
  heroHomeModernSolid,
  heroUsersSolid,
  heroUserGroupSolid,
  heroShieldCheckSolid,
  heroDocumentTextSolid,
  heroCog6ToothSolid,
  heroArrowRightOnRectangleSolid,
  heroEyeSolid,
  heroPencilSolid,
  heroTrashSolid
} from '@ng-icons/heroicons/solid';
import { authInterceptor } from './shared/interceptors/auth.interceptor';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideAnimationsAsync(),
    provideIcons({
      heroHomeModern,
      heroUsers,
      heroUserGroup,
      heroShieldCheck,
      heroDocumentText,
      heroPresentationChartLine,
      heroBell,
      heroCalendar,
      heroMap,
      heroChatBubbleLeftRight,
      heroCog6Tooth,
      heroArrowRightOnRectangle,
      heroBars3,
      heroXMark,
      heroMagnifyingGlass,
      heroPlus,
      heroPencil,
      heroTrash,
      heroEye,
      heroEyeSlash,
      heroChevronRight,
      heroChevronDown,
      heroChevronUp,
      heroChevronLeft,
      heroCheck,
      heroExclamationTriangle,
      heroInformationCircle,
      heroArrowPath,
      heroArrowsPointingOut,
      heroArrowsPointingIn,
      heroBuildingLibrary,
      heroFingerPrint,
      heroIdentification,
      heroBriefcase,
      heroChartBar,
      heroClipboardDocumentCheck,
      heroSquare3Stack3d,
      heroArchiveBox,
      heroQueueList,
      heroUserCircle,
      heroBuildingOffice2,
      heroShieldExclamation,
      heroCheckCircle,
      heroExclamationCircle,
      // Solids
      heroHomeModernSolid,
      heroUsersSolid,
      heroUserGroupSolid,
      heroShieldCheckSolid,
      heroDocumentTextSolid,
      heroCog6ToothSolid,
      heroArrowRightOnRectangleSolid,
      heroEyeSolid,
      heroPencilSolid,
      heroTrashSolid
    })
  ]
};
